# Site settings
title: Sn0wbird's Coding Blog
description: From Zero to Hero
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sn0wbird
user_description: An English Developer-in-Training living in London
user_title: Apprentice
email: 
twitter_username: 
github_username:  Sn0wbird
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
